name: 'Setup Cargo Binaries'
description: 'Sets up a Rust Cargo binary crate'

inputs:
  bin-name:
    description: "The binary crate's name"
    required: true
  args:
    description: 'Additional Cargo arguments'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - id: cache_installation
      uses: actions/cache@v2
      with: 
        path: ~/.cargo/
        key: ${{ runner.os }}-setup-${{ inputs.bin-name }}
      
    - id: install_binary
      run: cargo install ${{ inputs.bin-name }} ${{ inputs.args }}
      shell: bash
