name: 'Setup Cargo Binaries'
description: 'Sets up a Rust Cargo binary crate'

inputs:
  bin-name:
    description: "The binary crate's name"
    required: true
  args:
    description: 'Additional Cargo arguments'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - id: Cache Installation and Search for previous Caches
      if: ${{ runner.os != 'Windows' || matrix.os != 'windows-latest' }}
      uses: actions/cache@v2
      with: 
          path: $HOME/.cargo/bin
          key: ${{ runner.os }}-setup-${{ inputs.bin-name }}

     - id: Cache Installation and Search for previous Caches
      if: ${{ runner.os == 'Windows' || matrix.os == 'windows-latest' }}
      uses: actions/cache@v2
      with: 
          path: $UserProfile/.cargo/bin
          key: windows-setup-${{ inputs.bin-name }}

    - id: Install Binary
      run: cargo install ${{ inputs.bin-name }} ${{ inputs.args }}
