name: Test Action

on:
  push:
    branches: [main]
    paths:
      - 'action.yml'
      - '.github/workflows/test-action.yml'
  
  pull_request:
    branches: [main]
    paths:
      - 'action.yml'
      - '.github/workflows/test-action.yml'

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-cargo-bin@v1
        with:
          bin-name: cross

      - name: Test Cross
        run: cross -h
